// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuatH1uWUmea6GXzC7GAHrJvFB-QgO3c',
    appId: '1:308074927805:web:de6cf3f53f64403973c9d4',
    messagingSenderId: '308074927805',
    projectId: 'fruteapp',
    authDomain: 'fruteapp.firebaseapp.com',
    storageBucket: 'fruteapp.firebasestorage.app',
    measurementId: 'G-P3YYMZD6N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPZ17x-BV7M8PCI4d43-gHQB1INjevXA',
    appId: '1:308074927805:android:f5b8db530721967073c9d4',
    messagingSenderId: '308074927805',
    projectId: 'fruteapp',
    storageBucket: 'fruteapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbkq6ocDHZVlLnTOnoBCoP2B4w3aoAJ_E',
    appId: '1:308074927805:ios:00484b62d25ef51673c9d4',
    messagingSenderId: '308074927805',
    projectId: 'fruteapp',
    storageBucket: 'fruteapp.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbkq6ocDHZVlLnTOnoBCoP2B4w3aoAJ_E',
    appId: '1:308074927805:ios:00484b62d25ef51673c9d4',
    messagingSenderId: '308074927805',
    projectId: 'fruteapp',
    storageBucket: 'fruteapp.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMuatH1uWUmea6GXzC7GAHrJvFB-QgO3c',
    appId: '1:308074927805:web:4e981bb24b729dce73c9d4',
    messagingSenderId: '308074927805',
    projectId: 'fruteapp',
    authDomain: 'fruteapp.firebaseapp.com',
    storageBucket: 'fruteapp.firebasestorage.app',
    measurementId: 'G-5Q8C10NCHH',
  );
}
